INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Teresa','Zamorano Martínez','01/01/1983','659004056/','','4','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Victoriano','Mármol Vivas','01/01/1980','665842732/','','4','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Sigrum','Potillo Gallardo','01/01/1917','617248374/','','4','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Sagrario','Morales','01/01/1973','627276760/','','4','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Isabel','Durán','01/01/1917','651472629/','','4','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Teresa','Cardado Montiel','01/01/1917','615866412/','','4','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('José Francisco','Gil Cardado','01/01/2002','','','4','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Paula ','Barrau Portillo','01/01/2002','','','4','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Cristina','Ruíz de la Torre','01/01/2000','','','4','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Salvadora','Pascual Benítez','01/01/1917','','','4','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Estefanía','Sánchez Serrano','01/01/1994','692864485/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('José','Villa Brieva','01/01/1975','616102386/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Alfonso','López Gémar','01/01/1917','676598291/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Pilar ','Arjona García','01/01/1917','679446413/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Eli','Bandera Pacheco','01/01/1917','693244346/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Gabriel','Ramírez Bandera','01/01/2013','','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Charo','Fuentes','01/01/1972','653790937/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mariam','Pérez Alcalde','01/01/1987','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Gema','García Raggio','01/01/1968','675618271/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('José','Cano Bernal','01/01/1968','655679229/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Alfonso','Prados Gordillo','01/01/1966','619132736/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Ana','Gómez Sánchez','01/01/1972','699481839/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Inés','Escalona Castillo','01/01/1976','675505136/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Javier','del Río Guirado','01/01/1964','644425047/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mercedes','Cerezo Márquez','01/01/1968','619455453/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Victoria','del Río Guirado','01/01/1917','656421710/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Miguel','Montosa Alga','01/01/1968','609506369/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María José','Romero','01/01/1917','665769901/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Juán de la Cruz','Aguayo Díaz','01/01/1918','645929261/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mercedes','Berrio Sánchez-Pacheco','01/01/1972','636279839/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Gema','Cano García','01/01/2001','689296202/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Marta','Cano García','01/01/2003','689296202/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Alberto ','Jiménez Gómez','01/01/2000','600801548/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Andrea','Jiménez Gómez','01/01/2002','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Miriam','Del Río Cerezo','01/01/1999','696267620/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Laura','Luque Ruíz','01/01/1917','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Elena','Montosa del Río','01/01/1999','634617642/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Victoria','Montosa del Río','01/01/2003','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Genoveva','González Escalante','01/01/1917','678969655/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Charo','Vega Luque','01/01/1917','636115821/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Rosario','López Muñoz','01/01/1917','678252855/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Lucía','Vazquez','01/01/2003','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Charo','Castañeda','01/01/1917','656691224/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Rosa María','Aguilar Piñero','01/01/1917','666640143/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Teresa','Aguilar Díez','01/01/1998','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Toñi ','Selma Pérez','01/01/1917','676183637/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Elvira','Sánchez Mejías','01/01/1917','616640300/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Raquel','García Sánchez','01/01/1917','699312832/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Gema ','Zarzuela','01/01/1917','619511635/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Inmaculada','García García','01/01/1917','678673887/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mercedes','Albacete Corpas','01/01/1917','660083915/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Elena','Millán Villalobos','01/01/1917','654258502/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Victora','Palma Millán','01/01/2013','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Francisco José','Oliva Flores','01/01/1917','696582994/952622883/ciscooliva72@gmail.com','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Rosa María','Catequista','01/01/1917','605348806/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('José Antonio','Sánchez','01/01/1917','605348805/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María','Plaza','01/01/1917','653956841/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Remedios (Remi)','Vegas García','01/01/1917','655789922/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Rocío','Madrid','01/01/1917','626401556/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Pilar ','Martínez Fraile','01/01/1917','605027537/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Jesús','Pérez-Rioja Navarro','01/01/1983','','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Yolanda','Piñero','01/01/1980','654753763/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Miguel','Adalid','01/01/1980','615198026/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Lucía','Arrebola','01/01/1917','','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Susana','García Torres','01/01/1981','677331570/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Loli','Esteo','01/01/1987','667950513/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('David','Del Río','01/01/1993','662502224/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Paula','Rubio','01/01/1999','626975810/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Marta','Rueda','01/01/1977','619037363/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Celia','Gómez Torres','01/01/1982','636286342/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Antonio','Luque','01/01/1975','636790323/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Pilar ','Cantos Jiménez','01/01/1971','615132298/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Álvaro','Gemar López','01/01/1982','605855737/','','1','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Ana María','Almudever López','01/01/1984','616123685/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Nuria ','Romero Lara','01/01/1974','627570097/','','1','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Jesús','Moreno Roldán','01/01/1974','627570097/','','1','V')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Juan José','Haro Fabuel','01/01/1917','670828233/','','3','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Cristina','Antúnez Rodríguez','01/01/1917','659081427/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Amador','Díaz Podadera','01/01/1961','693600765/','','3','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Daniel ','Fuster Caro','01/01/1991','654531406/','','3','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Cristina','Jiménez Ruíz','01/01/1996','658445512/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Toni','Almario','01/01/1984','618163736/','','3','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mabel','Caro López','01/01/1965','652887703/mabelcarolopez@yahoo.es','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Nuria ','Caro López','01/01/1967','654547847/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Victoria','González Valderrama','01/01/1917','661397335/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Patricia','González San-Segundo','01/01/1917','600366966/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Teresa ','Aldea','01/01/1917','645766077/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mabel','Marquez Recio','01/01/1978','699874132/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Nacho','Caro López','01/01/1975','647989430/','','3','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Esther','Díaz Caro','01/01/1996','622365065/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Marta','Fuster Caro','01/01/2003','693615685/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Patxi','Velasco Fano','01/01/1917','673635111/','','3','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Susana','Salas Cobaleas','01/01/1917','652107490/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Cristina','Vera','01/01/1917','658961295/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Salvador','González','01/01/1917','658961294/','','3','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Judit','Velasco Salas','01/01/1917','','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Emi','García','01/01/1917','644406010/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Ángela','Ramos Villodres','01/01/1917','','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Teresa','Malagón Torres','01/01/1917','','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Maribel','Lluberes Paulino','01/01/1917','692220203/','','3','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Isabel María','Ruíz','01/01/1917','627426698/','','3','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María','Montes Martín','01/01/1999','605540933/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Andrés','Sotorríos Pérez','01/01/2000','607869220/','','5','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Rafael','Cuenca Moreno','01/01/1996','659334933/','','5','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Alejandro','Guzmán Platero','01/01/1997','686309625/','','5','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Victoria','Lupiañez Bravo','01/01/1994','661170624/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Francisco','Quero Requena','01/01/1994','650359889/','','5','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Álvaro ','Guardiola','01/01/1992','627680993/','','5','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Ángela','Quero Requena','01/01/1990','679082594/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Victoria','Ramos','01/01/1917','659106857/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mercedes','Gallardo Quero','01/01/1917','687592187/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Pilar','Gallardo Quero','01/01/1917','717772230/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('José ','Pastor','01/01/1917','607594237/','','5','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Carmen','Ávila','01/01/1917','606032193/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Isabel ','Larrubia','01/01/1917','661494357/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Nuria','Sotorrío Pérez','01/01/1992','647495350/','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Marta','Ramos Díaz de la Rocha','01/01/1917','','','5','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Francisco Javier','Cuenca','01/01/1917','','','5','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Carmen','López','01/01/2017','','','6','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Regina ','del Río Aguilera','01/01/1991','','','6','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Sara María','del Río Aguilera','01/01/1989','','','6','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María Jesús','Pacheco Rodríguez','01/01/1989','','','6','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Jose Luís ','Carmona Jiménez','01/01/1994','','','6','V')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mariló','Villén Olalla','01/01/1917','','','7','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Paula','Morales Molina','01/01/1917','','','7','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Javier','Martín','01/01/1917','','','7','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Diego ','Palacios Gómez ','01/01/1917','','','7','V')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Raquel','Fernández Muñoz','01/01/1997','','','8','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Águeda','Fernández Muñoz','01/01/1997','','','8','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Isabel','Fernández Muñoz','01/01/1997','','','8','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Tania','Bentum','01/01/1998','','','9','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Paqui','Aguilar Nicolás','01/01/1975','666281761/','','10','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Francisco José','Sánchez Heras','01/01/1981','','','10','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Juan Pedro','Sánchez Aguilar','01/01/2013','','','10','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Pablo ','Sánchez Aguilar','01/01/2016','','','10','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Joaquín ','García Arias','01/01/1981','686854441/','','10','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Esther ','Ortega Palop','01/01/1975','610882416/','','10','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Guillermo','Montosa Ortega','01/01/2010','','','10','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Lidia','Castro Barcos','01/01/1917','654942341/','','10','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Lili','Ramirez Sidadmed','01/01/1999','602337641/','','10','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Belén ','Armenteros Jiménez','01/01/1991','686246216/','','10','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Elena ','Armenteros Jiménez','01/01/2000','649201178/','','10','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Sergio','García Almodóvar','01/01/1917','','','10','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Rocio','Aranda González','01/01/1917','','','10','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Alberto ','Villena Fernández','01/01/1998','','','2','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Miriam ','Torres Bravo','01/01/1997','','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Angelines ','Morales Fernández','01/01/1983','','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('M Paz','Navarro González','01/01/1970','','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mª Carmen',' Soto','01/01/1975','','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Paula','Fontalba','01/01/1991','645597721/','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mónica ','Flores González','01/01/1976','','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Francisco J. ','Abolacio García','01/01/1996','','','2','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Cristina ','Ortega González','01/01/1996','654206652/','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Marta ','Aragón Segarra','01/01/1992','652113408/','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Rocío ','Naveros Zayas','01/01/1996','651995902/','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mercedes ','Fernández','01/01/1972','','','2','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Pilar ','Aurrecochea','01/01/1972','','','2','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Susana ','Torres Borrego','01/01/1917','','','11','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Aida ','Bedoya Torres','01/01/2004','','','11','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Lucía ','Martín Pérez','01/01/2000','','','11','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Mª Eugenia','Civantos Serrato','01/01/1917','','','11','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Laura ','Cabrera Macías','01/01/1917','','','11','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Juana ','Bueno Avilés','01/01/1917','','','11','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María José ','Vargas Rodríguez','01/01/1917','','','11','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('María José ','Naranjo Jiménez','01/01/1977','','','12','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Margarita ','Texeira Pérez','01/01/1966','','','12','M')

INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Paco','Ríos','01/01/1997','','','13','V')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Irene','Gemar Godoy','01/01/1996','','','13','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Alejandra','Maldonado Ruíz','01/01/1996','','','13','M')
INSERT INTO PERSONA ( Nombre, Apellido, FechaNacimiento, Telefono, Enfermedad, ParroquiaID, Sexo) Values ('Cristian','Cuevas Zamora','01/01/1996','','','13','V')
